#ifndef ESP32_REMOTECAMERA_BATTERYERROR_H
#define ESP32_REMOTECAMERA_BATTERYERROR_H

typedef enum BatteryError {
    BATTERY_ERROR_NONE = 0,
    BATTERY_ERROR_INVALID_PARAMETER,
    BATTERY_ERROR_GENERIC_FAILURE
} BatteryError;

#endif //ESP32_REMOTECAMERA_BATTERYERROR_H
