#ifndef ESP32_REMOTECAMERA_WIFIERROR_H
#define ESP32_REMOTECAMERA_WIFIERROR_H

typedef enum WifiError {
    WIFI_ERROR_NONE = 0,
    WIFI_ERROR_WIFI_NOT_INITIALIZED,
    WIFI_ERROR_INVALID_WIFI_MODE,
    WIFI_ERROR_DISCONNECTING,
    WIFI_ERROR_CONNECTING,
    WIFI_ERROR_GENERIC_FAILURE = -1
} WifiError;

#endif //ESP32_REMOTECAMERA_WIFIERROR_H
