#ifndef ESP32_REMOTECAMERA_WEBSERVERERROR_H
#define ESP32_REMOTECAMERA_WEBSERVERERROR_H

typedef enum {
    WEBSERVER_ERROR_NONE = 0,
    WEBSERVER_ERROR_GENERIC_FAILURE = -1
} WebserverError;

#endif //ESP32_REMOTECAMERA_WEBSERVERERROR_H
