#ifndef ESP32_REMOTECAMERA_INTERNALSTORAGE_H
#define ESP32_REMOTECAMERA_INTERNALSTORAGE_H

#include "Utils.h"
#include "StorageError.h"
#include <stdio.h>

#endif //ESP32_REMOTECAMERA_INTERNALSTORAGE_H
