#ifndef ESP32_REMOTECAMERA_STORAGEERROR_H
#define ESP32_REMOTECAMERA_STORAGEERROR_H

typedef enum StorageError {
    STORAGE_ERROR_NONE = 0,
    STORAGE_ERROR_INVALID_PARAMETER,
    STORAGE_ERROR_PARTITION_NOT_FOUND,
    STORAGE_ERROR_KEY_NOT_FOUND,
    STORAGE_ERROR_INVALID_KEY,
    STORAGE_ERROR_INVALID_VALUE,
    STORAGE_ERROR_NVS_CLOSED,
    STORAGE_ERROR_NOT_ENOUGH_SPACE,
    STORAGE_ERROR_FILE_NOT_FOUND,
    STORAGE_ERROR_GENERIC_FAILURE = -1,
} StorageError;

#endif //ESP32_REMOTECAMERA_STORAGEERROR_H
