#ifndef ESP32_REMOTECAMERA_INTERNALSTORAGECOMMON_H
#define ESP32_REMOTECAMERA_INTERNALSTORAGECOMMON_H

#include "Utils.h"

#define LOG_TAG "InternalStorage:"__FILE__
#define undeclared static

#endif //ESP32_REMOTECAMERA_INTERNALSTORAGECOMMON_H
